// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtuFYa6JUw3aXvuDRDJKlo_EZffMg-LDI',
    appId: '1:647403013672:web:c477643c5aecfc7d26171d',
    messagingSenderId: '647403013672',
    projectId: 'porkin-io-app',
    authDomain: 'porkin-io-app.firebaseapp.com',
    storageBucket: 'porkin-io-app.appspot.com',
    measurementId: 'G-06MBPY3FXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxnoJm6OOG2Fz0GKe5GYMaaniHWsxgAE0',
    appId: '1:647403013672:android:0ad47b59f8af92c326171d',
    messagingSenderId: '647403013672',
    projectId: 'porkin-io-app',
    storageBucket: 'porkin-io-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADr3G0I98pRZsDUEOuZtLNtDZL2XjOQgs',
    appId: '1:647403013672:ios:ac89b2fe1644d1f826171d',
    messagingSenderId: '647403013672',
    projectId: 'porkin-io-app',
    storageBucket: 'porkin-io-app.appspot.com',
    iosClientId: '647403013672-6ulrso6denk3414jm46j4a87tg7erhp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADr3G0I98pRZsDUEOuZtLNtDZL2XjOQgs',
    appId: '1:647403013672:ios:ac89b2fe1644d1f826171d',
    messagingSenderId: '647403013672',
    projectId: 'porkin-io-app',
    storageBucket: 'porkin-io-app.appspot.com',
    iosClientId: '647403013672-6ulrso6denk3414jm46j4a87tg7erhp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoFlutter',
  );
}
